name: Shoorka
on: push

jobs:
  terraform:
    name: Terraform Infrastructure
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Format Terraform configuration
        id: fmt
        working-directory: ./terraform
        run: terraform fmt

      - name: Initialize Terraform
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Validate Terraform configuration
        id: validate
        working-directory: ./terraform
        run: terraform validate

      - name: Plan Terraform configuration
        id: plan
        working-directory: ./terraform
        run: terraform plan

      - name: Apply Terraform configuration
        id: apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: List where I am
        run: ls -la
